#include <def.h>

void Ode1low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham1low (int neq,solution *u,parameters *params);
void Jac1low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode2low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham2low (int neq,solution *u,parameters *params);
void Jac2low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode3low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham3low (int neq,solution *u,parameters *params);
void Jac3low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode4low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham4low (int neq,solution *u,parameters *params);
void Jac4low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode5low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham5low (int neq,solution *u,parameters *params);
void Jac5low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode6low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham6low (int neq,solution *u,parameters *params);
void Jac6low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode7low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham7low (int neq,solution *u,parameters *params);
void Jac7low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode8low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham8low (int neq,solution *u,parameters *params);
void Jac8low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode9low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham9low (int neq,solution *u,parameters *params);
void Jac9low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode10low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
val_type0 Ham10low (int neq,solution *u,parameters *params);
void Jac10low (int neq, val_type t,val_type0 *u,lowfloat0 *Jac,parameters *params);
void Ode11low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
void Ode12low (int neq, val_type t,val_type0 *u,val_type0 *f,parameters *params);
