#
# make : 20-04-2017 
#
# Description: Makefile for compiling IRK-NEWTON project.
# System: Ubuntu 16.04 lts (64 bits)
# 

# Compiler.
SYS = Linux
CC = /usr/bin/gcc

# Wolfram Mathematica. 
MATHLINKPATH = $(MATHEMATICA_HOME)/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions
MPREP = $(MATHLINKPATH)/mprep

# Compiler options.
LIBFLAGS=-L$(MATHLINKPATH)

FLAGS=-I$(MATHLINKPATH) -O2 -Wall -std=c99 -fno-common -mfma
OMP_FLAGS=-fopenmp

# Objects
OBJECTS = GaussTerminal.o GaussInitData.o GaussCommon.o GaussUserProblem.o GaussCoefficients.o 
REALOBJECTS = math-Gausstm.o math-Gauss.o GaussCommon.o GaussUserProblem.o GaussCoefficients.o 

.PHONY: clean help 

all : 
	make clean;
	make term-Gauss;
	make math-Gauss;

term-Gauss: $(OBJECTS) 
	${CC} $(OBJECTS) ${OMP_FLAGS} -lm -lquadmath -llapacke -lblas -o GaussTerminal.exe

math-Gausstm.c : math-Gauss.tm
	${MPREP} math-Gauss.tm -o math-Gausstm.c

%.o: %.c prec.h def.h 
	${CC}  ${FLAGS} ${OMP_FLAGS} -c -I./  $<

math-Gauss : $(REALOBJECTS)    
	${CC}  $(REALOBJECTS) $(LIBFLAGS) ${OMP_FLAGS} -lML64i4 -lm -lrt -lstdc++ -luuid -ldl -llapacke -lblas  -o math-Gauss.exe 

clean :
	rm -rf *.o *~ core *tm.* *.exe 

help:
	@echo "Valid targets;"
	@echo " term-Gauss"
	@echo " math-Gauss"




